### ISSUE TITLE
Planning overview (revised!)

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-environmental-layers#134]
This new library is rapidly seeing many new layers, and we need some additional structure to help make the display/management of this amazing data smoother. This would include:

## Documentation

* [ ] improved workflow for incorporating and accepting new layers (submission template) (see below)

## Structure

* [ ] improved layer management system with bounding boxes + zooms from layer metadata
* [ ] standardization of layer types (tile, rss, csv, geojson, polygonal, also subtypes like spreadsheet, esri)
    * [ ] and code to make adding new layers of a generic type easier
* [ ] consolidation and standardization of all layers
* [ ] reduction of redundant layer code
* [ ] layer metadata -- description, source, docs for each, relevant bounding box and zoom levels, version, in a single file

## UI

See mockup below!

* [ ] UI for highlighting new layers in current viewport as you drag/zoom #133 
* [ ] unique-id based layer toggling in URL hash - related to #33 
* [ ] standardization of per-item popover UI (image, description, source, toggle, link) #59 
* [ ] examples for how to enable/disable layers from javascript (i.e. from a separate button or checkbox for example)
* [ ] examples for how to open the map at a given location and zoom level using URL hashes: https://github.com/mlevans/leaflet-hash
* [ ] search for a location to re-center upon with a :mag: button and autocomplete geocoder (like at https://github.com/publiclab/leaflet-blurred-location)
* [ ] minimial 'dots' ui #123 

## Testing

* [ ] Adding tests! #71 

*******

### New layers

* [ ] WaterReporter.org (uses GeoJSON - http://leafletjs.com/examples/geojson/ , API : http://docs.waterreporter.org/?Javascript#your-first-request)
* [ ] watershed mapper -- for which way water flows? https://www.epa.gov/waterdata/waters-geoviewer
* [ ] public comments map via Scott Eustis (i'll add more detail later)

*******

![image](https://user-images.githubusercontent.com/24359/54041993-1cc43a80-4197-11e9-9939-5cfa67432c50.png)

Takes over for #1

**Comment by sidntrivedi012** [comment]
@jywarren The thread looks really nice. Would like to ask that can we write tests in Jest? Its kinda nice and efficient to use for Javascript testing.

**Comment by sidntrivedi012** [comment]
You can find more info about jest here - https://jestjs.io/

**Comment by avsingh999** [comment]
@sidntrivedi012 I like your thinking but I do not understand Why we use jest for Test because In a test we have to enable all layers like @jywarren open this issue https://github.com/publiclab/leaflet-environmental-layers/issues/101.Please correct me if  I am wrong @jywarren  @sidntrivedi012 
thanks  : )

**Comment by jywarren** [comment]
We currently use Jasmine for a number of tests and so would lean that
direction for consistency across PL libraries... and it tests HTML as well
(it wasn't clear that Jest does this, but maybe?). Can we move to the
dedicated testing issue for more discussion, this is great!!!

**Comment by sidntrivedi012** [comment]
@jywarren Sure. Jasmine is great. And it's really a very nice notion to maintain consistency in the project.

**Comment by vaarigupta** [comment]
@jywarren  I am an **outreachy applicant** and am interested to work on it. Please assign me this issue to work

**Comment by ananyaarun** [comment]
@jywarren , @gauravano  I went through the project Extend Leaflet Environmental Layers with new layer menu and layer addition workflow carefully.It looks very interesting to me !! I did start contributing to this repository as well apart from plots2 to try and understand the workflow here.

I have also worked on a project closely related to this previously.
Here is the link https://github.com/ananyaarun/Open-Street-Maps
A map i particularly visualized using leaflet can be seen here 
https://ananyaarun.github.io/OSM3/

I would love to apply to this project as well :) Can i have more info in this regard ? Can i record my contribution and experience for this project in the main outreachy website itself ? 

Thanks!

**Comment by gauravano** [comment]
Hey @vaarigupta, this issue is for Outreachy and so not available for claiming. But, we would love to have your help with other issues of this repo https://github.com/publiclab/leaflet-environmental-layers/issues/. Thanks!

**Comment by gauravano** [comment]
> I would love to apply to this project as well :) Can i have more info in this regard ? Can i record my contribution and experience for this project in the main outreachy website itself ?

hey @ananyaarun, if you're eligible for raising multiple proposals for a single org, then sure we would love to see your proposal. Yes, please go ahead and mention all the contributions you did in this repo. Thanks!

**Comment by vaarigupta** [comment]
> Hey @vaarigupta, this issue is for Outreachy and so not available for claiming. But, we would love to have your help with other issues of this repo https://github.com/publiclab/leaflet-environmental-layers/issues/. Thanks!

Ya I am willing to participate in outreachy this year. So please suggest me how can I make contribution?

**Comment by gauravano** [comment]
Hey @vaarigupta, I think for being able to raise proposal, you need to solve a issue of this project. So, go through https://github.com/publiclab/leaflet-environmental-layers/issues and start with issues, which looks good to you. We don't have much `first-timers-only` issues in this project, but I will see if some can be created.

Thanks!

**Comment by jywarren** [comment]
Hi! Actually there are so many parts of this that we expect it will take more than one Outreachy term to complete, so we are happy to have contributions before then as well! Please feel free to pick out a piece of this and give it a try. I might recommend https://github.com/publiclab/leaflet-environmental-layers/issues/156 is mainly the installation of a plugin, so it could make a good self-contained issue to start with!

**Comment by ananyaarun** [comment]
@jywarren @gauravano is extending leaflet layers an outreachy project or a gsoc project or both ?
I see it listed under both the outreachy website and this link for gsoc ideas 
https://publiclab.org/wiki/gsoc-ideas

**Comment by gauravano** [comment]
It's part of both

**Comment by sagarpreet-chadha** [comment]
Added https://github.com/publiclab/leaflet-environmental-layers/issues/174 to the list of new layers 🗺 !

**Comment by nstjean** [comment]
Where do users go to use this full map and all its possibilities? I know MapKnitter.com uses mapping, but only for one layer. https://publiclab.org/maps/ has environmental layers listed on the map at the top, but it doesn't look the same as it does using the /example/ directory in my dev environment.

Basically, is this used only within PublicLab.org and other of our sites, or is there/will there be a site users can go to create their own maps to share?

**Comment by sagarpreet-chadha** [comment]
Hey @nstjean ,
Yes we have done some changes recently and we will soon publish the new version.  I dont know if this library is integrated to other websites apart from PL.org and mapknitter.

Yes definately we will work on making a utility that will generate maps with layer and an iframe link that people can use to embed the map on their websites. Thanks!

I hope this helps!

**Comment by jywarren** [comment]
Adding here -- a search box so you can quickly search for locations on the earth would be great! Not open by default but behind a magnifying glass icon maybe, that pops open and then you can start searching.

**Comment by crisner** [comment]
@jywarren I have checked off a few tasks that had been done recently from the checklist above.

**Comment by jywarren** [comment]
Awesome!
